name: Cypher Queries

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:4.3
        ports:
          - 7687:7687
        env:
          NEO4J_AUTH: neo4j/s3cr3t
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4JLABS_PLUGINS: '["apoc", "graph-data-science"]'
        options: >-
          --health-cmd "cypher-shell -u neo4j -p s3cr3t 'RETURN 1'"
          --health-interval 5s
          --health-timeout 60s
          --health-retries 12

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run fetchAsciiDoc
      - run: npm run checkQueries
        env:
          NEO4J_DATABASE_URI: 'bolt://localhost:7687'
          NEO4J_DATABASE_USER: 'neo4j'
          NEO4J_DATABASE_PASSWORD: 's3cr3t'
